# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(986, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.addGunPushButton = QtWidgets.QPushButton(self.groupBox)
        self.addGunPushButton.setObjectName("addGunPushButton")
        self.gridLayout_4.addWidget(self.addGunPushButton, 1, 0, 1, 1)
        self.delGunPushButton = QtWidgets.QPushButton(self.groupBox)
        self.delGunPushButton.setObjectName("delGunPushButton")
        self.gridLayout_4.addWidget(self.delGunPushButton, 1, 1, 1, 1)
        self.gunLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.gunLineEdit.setObjectName("gunLineEdit")
        self.gridLayout_4.addWidget(self.gunLineEdit, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.addNamePushButton = QtWidgets.QPushButton(self.groupBox)
        self.addNamePushButton.setObjectName("addNamePushButton")
        self.gridLayout_3.addWidget(self.addNamePushButton, 1, 0, 1, 1)
        self.delNamePushButton = QtWidgets.QPushButton(self.groupBox)
        self.delNamePushButton.setObjectName("delNamePushButton")
        self.gridLayout_3.addWidget(self.delNamePushButton, 1, 1, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout_3.addWidget(self.nameLineEdit, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 1, 1, 1)
        self.gunListWidget = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gunListWidget.sizePolicy().hasHeightForWidth())
        self.gunListWidget.setSizePolicy(sizePolicy)
        self.gunListWidget.setObjectName("gunListWidget")
        self.gridLayout_2.addWidget(self.gunListWidget, 1, 0, 1, 1)
        self.nameListWidget = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameListWidget.sizePolicy().hasHeightForWidth())
        self.nameListWidget.setSizePolicy(sizePolicy)
        self.nameListWidget.setObjectName("nameListWidget")
        self.gridLayout_2.addWidget(self.nameListWidget, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.voteTableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.voteTableWidget.setObjectName("voteTableWidget")
        self.voteTableWidget.setColumnCount(0)
        self.voteTableWidget.setRowCount(0)
        self.gridLayout_5.addWidget(self.voteTableWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.tidLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tidLineEdit.setObjectName("tidLineEdit")
        self.horizontalLayout_2.addWidget(self.tidLineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pagesLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pagesLineEdit.setObjectName("pagesLineEdit")
        self.horizontalLayout_2.addWidget(self.pagesLineEdit)
        self.startPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startPushButton.setObjectName("startPushButton")
        self.horizontalLayout_2.addWidget(self.startPushButton)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.scheduleLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.scheduleLineEdit.setObjectName("scheduleLineEdit")
        self.horizontalLayout_2.addWidget(self.scheduleLineEdit)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.trueloveLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.trueloveLineEdit.setObjectName("trueloveLineEdit")
        self.horizontalLayout_2.addWidget(self.trueloveLineEdit)
        self.loadSettingPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadSettingPushButton.setObjectName("loadSettingPushButton")
        self.horizontalLayout_2.addWidget(self.loadSettingPushButton)
        self.saveSettingPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveSettingPushButton.setObjectName("saveSettingPushButton")
        self.horizontalLayout_2.addWidget(self.saveSettingPushButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NGA萌战计票工具"))
        self.groupBox.setTitle(_translate("MainWindow", "选手信息"))
        self.label_4.setText(_translate("MainWindow", "昵称"))
        self.label_3.setText(_translate("MainWindow", "名称"))
        self.addGunPushButton.setText(_translate("MainWindow", "增加"))
        self.delGunPushButton.setText(_translate("MainWindow", "删除"))
        self.addNamePushButton.setText(_translate("MainWindow", "增加"))
        self.delNamePushButton.setText(_translate("MainWindow", "删除"))
        self.groupBox_2.setTitle(_translate("MainWindow", "统计信息"))
        self.label.setText(_translate("MainWindow", "帖子TID"))
        self.label_2.setText(_translate("MainWindow", "页数"))
        self.startPushButton.setText(_translate("MainWindow", "开始"))
        self.label_5.setText(_translate("MainWindow", "赛程"))
        self.label_6.setText(_translate("MainWindow", "真爱倍率"))
        self.loadSettingPushButton.setText(_translate("MainWindow", "导入配置"))
        self.saveSettingPushButton.setText(_translate("MainWindow", "导出配置"))
